version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./data:/var/data
  report_app:
    image: reporting
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=8090
    ports:
      - '8090:8090'
volumes:
  db:
    driver: local
  report_app:
    driver: local